/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtRouteImport } from './routes/art'
import { Route as CvRouteImport } from './routes/cv'
import { Route as GaijinKitsuneRouteImport } from './routes/gaijin-kitsune'
import { Route as MusicRouteImport } from './routes/music'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as VideographyRouteImport } from './routes/videography'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtRoute = ArtRouteImport.update({
  id: '/art',
  path: '/art',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const GaijinKitsuneRoute = GaijinKitsuneRouteImport.update({
  id: '/gaijin-kitsune',
  path: '/gaijin-kitsune',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const VideographyRoute = VideographyRouteImport.update({
  id: '/videography',
  path: '/videography',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/art': typeof ArtRoute
  '/cv': typeof CvRoute
  '/gaijin-kitsune': typeof GaijinKitsuneRoute
  '/music': typeof MusicRoute
  '/photography': typeof PhotographyRoute
  '/videography': typeof VideographyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/art': typeof ArtRoute
  '/cv': typeof CvRoute
  '/gaijin-kitsune': typeof GaijinKitsuneRoute
  '/music': typeof MusicRoute
  '/photography': typeof PhotographyRoute
  '/videography': typeof VideographyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/art': typeof ArtRoute
  '/cv': typeof CvRoute
  '/gaijin-kitsune': typeof GaijinKitsuneRoute
  '/music': typeof MusicRoute
  '/photography': typeof PhotographyRoute
  '/videography': typeof VideographyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/art'
    | '/cv'
    | '/gaijin-kitsune'
    | '/music'
    | '/photography'
    | '/videography'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/art'
    | '/cv'
    | '/gaijin-kitsune'
    | '/music'
    | '/photography'
    | '/videography'
  id:
    | '__root__'
    | '/'
    | '/art'
    | '/cv'
    | '/gaijin-kitsune'
    | '/music'
    | '/photography'
    | '/videography'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtRoute: typeof ArtRoute
  CvRoute: typeof CvRoute
  GaijinKitsuneRoute: typeof GaijinKitsuneRoute
  MusicRoute: typeof MusicRoute
  PhotographyRoute: typeof PhotographyRoute
  VideographyRoute: typeof VideographyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/art': {
      id: '/art'
      path: '/art'
      fullPath: '/art'
      preLoaderRoute: typeof ArtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaijin-kitsune': {
      id: '/gaijin-kitsune'
      path: '/gaijin-kitsune'
      fullPath: '/gaijin-kitsune'
      preLoaderRoute: typeof GaijinKitsuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videography': {
      id: '/videography'
      path: '/videography'
      fullPath: '/videography'
      preLoaderRoute: typeof VideographyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtRoute: ArtRoute,
  CvRoute: CvRoute,
  GaijinKitsuneRoute: GaijinKitsuneRoute,
  MusicRoute: MusicRoute,
  PhotographyRoute: PhotographyRoute,
  VideographyRoute: VideographyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
